### ISSUE TITLE
Choice to direct resources to maindirectory and not subdirectories

### ISSUE THREAD

**Issue by henrikstranneheim** [robinandeer/cosmid#14]

**Comment by robinandeer** [comment]
This should be defined in "cosmid.yaml"

**Comment by henrikstranneheim** [comment]
yes, but how? As it is now you give it a main directory, but it automatically creates subdirectories.

**Comment by robinandeer** [comment]
Sorry, it was just a "note to self"

**Comment by robinandeer** [comment]
Could potentially lead to conflicting file names - I won't handle this intelligently for starters
